[package]
edition = "2021"
name = "fix-rapier"
version = "0.1.0"

[dependencies]
bevy = "0.8"
bevy_editor_pls = "*"
bevy_rapier2d = "0.17"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
